# Used by Travis CI to run our tests automatically
language: node_js
sudo: false
node_js:
  - "stable"

script: npm test

jobs:
  include:
    - stage: linting
      script: npm run test:lint
    - stage: unit test
      script: npm run test:coverage
    - stage: build
      script: npm run build
    - stage: npm release
      script: echo "Deploying to npm ..."
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        on:
          branch: master
